### ISSUE TITLE
method HEAD error

### ISSUE THREAD

**Issue by clouds56** [http-rs/surf#218]
I tried to use http HEAD method and it would hand
```rust
  async_std::task::block_on(async move {
    let res = surf::head("http://example.com").await.expect("surf");
    println!("{:?}", res);
  });
```
And if i replace http with https, it would give me exception
```
thread 'test_header' panicked at 'surf: ResponseBodyError(None): unknown error', http/src/lib.rs:84:19
```
If I replace `head` with `get`, all things goes well.

**Comment by Fishrock123** [comment]
Could you try with this in your `Cargo.toml`?

```toml
[dependencies]
surf = { version = "2.0.0-alpha.4", features =  ["h1-client"] }
```
