### ISSUE TITLE
hyper-client feature requires curl-client feature to work

### ISSUE THREAD

**Issue by igor-tk** [http-rs/surf#275]
I specify `hyper-client` as http backend. 

``` toml
[dependencies]
surf =  { version = "2.1", default-features = false, features = ["hyper-client", "encoding"] }
tokio = { version = "1", features = ["full"] }
```

``` rust
use surf;
use std::error::Error;

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let req = surf::get("https://httpbin.org/get");
    let resp = surf::client().send(req).await;
    println!("Resp: {:?}", resp);
    Ok(())
}
```

But, unfortunately, that does not work:
`thread 'main' panicked at 'not currently running on the Tokio runtime.'`

When I add `curl-client` to features:
`surf =  { version = "2.1", default-features = false, features = ["hyper-client", "encoding", "curl-client"] }`

It works.

But it seems like I have many unnecessary dependencies now (curl, isahc, etc.) that enabled by `curl-client` feature.

Can  `hyper-client` work without `curl-client`?
